### ISSUE TITLE
searchParams property is undefined on Android < 6

### ISSUE THREAD

**Issue by marcoow** [tchak/ember-url#1]
Although I think [this line](https://github.com/tchak/ember-url/blob/master/addon/index.js#L15) should fix the bug where a natively supported `URL` creates instances without a proper `searchParams` property, that doesn't seem to work correctly on Android < 6 where we get a `URL` instance with a `searchParams` property of `undefined`. That of course leads to errors with code like

```js
let lang = url.searchParams.get('lang');
```

/cc @sapeien

**Comment by tchak** [comment]
fixed with c68a2bc96841ace3ecb0b30e68f53fc4fb27e105
