### ISSUE TITLE
"URL.prototype" is undefined

### ISSUE THREAD

**Issue by Turbo87** [tchak/ember-url#3]
We recently updated a project to `ember-url@0.3.0` and noticed that the app no longer worked in Internet Explorer. We've managed to step through it and noticed that in the new `needPolyfill()` function `URL.prototype` is `undefined` in Internet Explorer, while in Chrome it is a proper object. I'm not sure if checking `URL.prototype !== undefined` will resolve the issue, but reverting to `v0.2.0` fixed the issue for us again... 🤔 

/cc @YoannDelpierre

**Comment by tchak** [comment]
are you saying IE has an `URL` object with no `.prototype` property? 🤦‍♂️

**Comment by Turbo87** [comment]
apparently, yes 🤷‍♂️

**Comment by tchak** [comment]
I released a `v0.4.0` let me know if it helps

**Comment by YoannDelpierre** [comment]
It's good with the new release.

Thanks @tchak
